---
title: "RLab4"
author: "Alexey Volkov"
date: '19 декабря 2018 г '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

#Пользуясь примером из лекции файл (5.0.R) проанализируйте данныео возрасте и физ. характеристиках молюсков

```{r}
data <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", header=TRUE, sep=",")
```

```{r}
summary(data)
```

```{r}
colnames(data)
```

```{r}
colnames(data) <- c("sex", "length", "diameter", "height", 
                "whole_weight", "shucked_weight",
                "viscera_weight", "shell_weight", "rings")

colnames(data)
```

```{r}
data$sex <- factor(c("Female", "Infant", "Male")[data$sex])
```

```{r}
par(mfrow=c(1,3))
hist(data$diameter, main = "Диаметр, мм")
hist(data$height, main = "Высота, мм")
hist(data$whole_weight, main = "Полный вес, гр")
```

#Видим ассиметрию https://en.wikipedia.org/wiki/Skewness
#и выбросы (от них нужно избавиться)
```{r}
par(mfrow=c(1,2)) 
plot(data$diameter, data$whole_weight,'p',main = "Зависимость веса от диаметра", xlab = "Диаметр", ylab = "Вес")
plot(data$height, data$whole_weight,'p',main = "Зависимость веса от высоты", xlab = "Высота", ylab = "Вес")
```

  Линейная модель зависимости веса от диаметра
  
```{r}
linear.model.1 <- lm(data$whole_weight ~ data$diameter)
summary(linear.model.1)
plot(linear.model.1)
```

 Линейная модель зависимости веса от высоты
 
```{r}
linear.model.2 <- lm(data$whole_weight ~ data$height)
summary(linear.model.2)
plot(linear.model.2)
```
 
 Линейная модель зависимости веса от длины
 
```{r}
linear.model.3 <- lm(data$whole_weight ~ data$length)
summary(linear.model.3)
plot(linear.model.3)
```

```{r}
data.filtered <- data[-c(1174,2621,165,891,1763,236,238,1210),]
data.filtered <- data.filtered %>% filter(height <= 0.25 & height > 0.0)
```

```{r}
linear.model.1.filt <- lm(data.filtered$whole_weight ~ data.filtered$diameter)
summary(linear.model.1.filt)
plot(linear.model.1.filt)
#plot(data.filtered$diameter, data.filtered$whole_weight, main = "Зависимость веса от диаметра")
```

```{r}
linear.model.2.filt <- lm(data.filtered$whole_weight ~ data.filtered$height)
summary(linear.model.2.filt)
plot(linear.model.2.filt)
#plot(data.filtered$height, data.filtered$whole_weight, main = "Зависимость веса от высоты")
```

```{r}
linear.model.3.filt <- lm(data.filtered$whole_weight ~ data.filtered$length)
summary(linear.model.3.filt)
plot(linear.model.3.filt)
```

```{r}
par(mfrow=c(1,2))
plot(data.filtered$diameter, data.filtered$whole_weight, main = "Зависимость веса от диаметра")
plot(data.filtered$height, data.filtered$whole_weight, main = "Зависимость веса от высоты")
```


```{r}
odds <- seq(1, nrow(data.filtered), by=2)
data.in <- data.filtered[odds,]
data.out <- data.filtered[-odds,]
```

```{r}
linear.model.half <- lm(data.in$whole_weight ~ data.in$diameter)
summary(linear.model.half)
plot(linear.model.half)
```

```{r}
weight.predict.1 <- predict(linear.model.half)
cor(data.in$whole_weight, weight.predict.1)
plot(data.out$whole_weight, weight.predict.1)
```

```{r}
weight.predict.1.out <- predict(linear.model.half, data.out)
cor(data.out$whole_weight, weight.predict.1.out)
plot(data.out$whole_weight, weight.predict.1.out)
```